from dataclasses import dataclass


@dataclass
class AssistantResponse:
    """
    Standard response generated by the Eyera AI Assistant.
    """

    text: str
    priority: str = "NORMAL"
    should_speak: bool = True
